channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=25.0.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - tensorflow-intel==2.18.0
  - tensorflow==2.18.0
name: mlflow-env
